#!/bin/sh
# /root/.xstartup

export XKL_XMODMAP_DISABLE=1
export XAUTHORITY=/root/.Xauthority
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

# Start dbus if not running
if ! pgrep -x dbus-daemon > /dev/null; then
    dbus-daemon --system --fork
fi

# Start XFCE session
startxfce4 &
